### ISSUE TITLE
Error downloading reference file

### ISSUE THREAD

**Issue by gstueck** [puxplaying/releasecompare#1]
Hi,
I've got the following error:

you chose xfce
--2020-02-16 11:32:57--  https://osdn.net/projects/manjaro/storage/xfce/19.0.0/
CA-Zertifikat »/etc/ssl/certs/ca-certificates.crt« wurde geladen
Auflösen des Hostnamens osdn.net (osdn.net)… 202.221.179.17
Verbindungsaufbau zu osdn.net (osdn.net)|202.221.179.17|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2020-02-16 11:32:59 FEHLER 404: Not Found.

grep: index.html: Datei oder Verzeichnis nicht gefunden
--2020-02-16 11:32:59--  https://osdn.net/projects/manjaro/storage/xfce/19.0.0/.txt
CA-Zertifikat »/etc/ssl/certs/ca-certificates.crt« wurde geladen
Auflösen des Hostnamens osdn.net (osdn.net)… 202.221.179.17
Verbindungsaufbau zu osdn.net (osdn.net)|202.221.179.17|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 404 Not Found
2020-02-16 11:33:00 FEHLER 404: Not Found.

BTW, thank you for puiblishing releasecompare!

**Comment by puxplaying** [comment]
Hi, thanks for the report.
This error happens because Manjaro already changed the Distribution Release local to 19.0 but they did not release updated ISO's yet as they are still in beta. As soon as Manjaro releases the official 19.0 ISO's you should get a working comparison again. 

This is unfortunately a problem that I can't easy work around or avoid and will most likely happen every time before a new ISO is released unless Manjaro can manage it to change the local release at the day they release the ISO's.

You can see the state of XFCE here https://osdn.net/projects/manjaro/storage/xfce/

> BTW, thank you for puiblishing releasecompare!

Glad that you find it useful, enjoy!

**Comment by puxplaying** [comment]
#https://github.com/puxplaying/releasecompare/commit/859c1d2f3298ba54a43d2b0d0a2a255e4bb4e993

**Comment by puxplaying** [comment]
The issue should be fixed with the latest changes.
